# Generated by Django 3.0.3 on 2022-10-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeMeli', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=25)),
                ('fatherName', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('serialMeli', models.CharField(max_length=10)),
                ('shomareSh', models.CharField(max_length=10)),
                ('serialSh', models.CharField(max_length=6)),
                ('seriSh', models.CharField(max_length=3)),
                ('sadereh', models.CharField(max_length=50)),
                ('ostan', models.CharField(max_length=50)),
                ('shahr', models.CharField(max_length=50)),
                ('neshaniShop', models.CharField(max_length=300)),
                ('codePosti', models.CharField(max_length=10)),
                ('telephonShop', models.CharField(max_length=8)),
                ('shomareParvane', models.CharField(max_length=50)),
                ('codeRehgiri', models.CharField(max_length=50)),
                ('teleHamrah', models.CharField(max_length=11)),
                ('bestareErtebat', models.CharField(choices=[('Dialup', 'Dialup Type'), ('GPRS', 'GPRS Type'), ('Combo', 'Combo Type'), ('WIFI', 'WIFI Type')], default='Dialup', max_length=6)),
                ('malekiyat', models.CharField(choices=[('ملکی', 'نوع ملکی'), ('سرقفلی', 'نوع سرقفلی'), ('استیجاری', 'نوع استیجاری')], default='ملکی', max_length=8)),
                ('mohlateEjareFrom', models.DateField()),
                ('mohlateEjareTo', models.DateField()),
                ('nameMoaref', models.CharField(max_length=20)),
                ('familyMoaref', models.CharField(max_length=25)),
                ('telMoaref', models.CharField(max_length=11)),
                ('neshaniMoaref', models.CharField(max_length=300)),
                ('shomareHesab', models.CharField(max_length=20)),
                ('nameBank', models.CharField(max_length=50)),
                ('shomareShaba', models.CharField(max_length=16)),
                ('shomareHesabTow', models.CharField(max_length=20)),
                ('nameBankTwo', models.CharField(max_length=50)),
                ('shomareShabaTwo', models.CharField(max_length=16)),
                ('nameFamilyKarshenas', models.CharField(max_length=100)),
                ('javazKasb', models.CharField(max_length=300)),
                ('ejarehName', models.CharField(max_length=300)),
                ('sanadMalek', models.CharField(max_length=300)),
                ('tsvirShenasnameh', models.CharField(max_length=300)),
                ('rooyeCartmeli', models.CharField(max_length=300)),
                ('poshtCartmeli', models.CharField(max_length=300)),
                ('tsvirEmzaMohr', models.CharField(max_length=300)),
                ('sabinFormFirst', models.CharField(max_length=300)),
                ('sabinFormTwo', models.CharField(max_length=300)),
                ('codeMeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.login', to_field='codeMeli')),
            ],
        ),
    ]
