# Generated by Django 3.0.3 on 2022-10-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='paziresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='birthday',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='mohlateEjareFrom',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='mohlateEjareTo',
            field=models.CharField(max_length=15),
        ),
    ]
