# Generated by Django 3.0.3 on 2022-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20221010_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='senf',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
